# Generated by Django 3.2.8 on 2021-10-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
